---
# tasks file for bareos (CentOS specific)

-   name: Remove bacula client
    yum:
        name: "{{ item }}"
        state: absent
    with_items:
        - bacula-common
        - bacula-client

-   name: Add bareos YUM repository
    template:
        src: centos_repo.repo.j2
        dest: /etc/yum.repos.d/bareos_centos_repo.repo
        owner: root
        group: root
        mode: 0644

-   name: Install bareos-fd
    yum:
        name: "{{ item }}"
        state: present
    with_items: "{{ mightydok_bareos_fd_packages }}"
